[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
presale = "E85K4x6CpSyDCkUNnH1ByLbAxmMCEYDheoA9DSLDM6Sd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/chaitanya/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
