[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
presale = "6wJQkGLgGqfDsDhgX6JCvRu8ngZsmGw2M6iy7bjCVMQS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./wallet.txt"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
